DROP TABLE PETSALE;
CREATE TABLE PETSALE(
	ID INT NOT NULL,
	Pet CHAR(20),
	SalePrice DECIMAL(6, 2),
	Profit DECIMAL(6, 2),
	SaleDate DATE
);

DROP TABLE FARMPET;
CREATE TABLE FARMPET(
    PET_ID INTEGER NOT NULL,
    ANIMAL VARCHAR(20),
    QUANTITY INTEGER
);

INSERT INTO PETSALE VALUES
	(1, 'Cat', 450.09, 100.47, '2018-05-29'),
	(2, 'Dog', 666.66, 150.76, '2018-06-01'),
    (3, 'Parrot', 50.00, 8.9, '2018-06-04'),
    (4, 'Hamster', 60.60, 12, '2018-06-11'),
    (5, 'Goldfish', 48.48, 3.5 ,'2018-06-14');

INSERT INTO FARMPET VALUES
	(1, 'Cat', 3),
	(2, 'Dog', 4),
	(3, 'Hamster', 2);

SELECT * FROM PETSALE;
SELECT * FROM FARMPET;

ALTER TABLE PETSALE 
ADD COLUMN Quantity INT;

SELECT * FROM PETSALE;

UPDATE PETSALE SET Quantity = 9 WHERE ID = 1;
UPDATE PETSALE SET QUANTITY = 3 WHERE ID = 2;
UPDATE PETSALE SET QUANTITY = 2 WHERE ID = 3;
UPDATE PETSALE SET QUANTITY = 6 WHERE ID = 4;
UPDATE PETSALE SET QUANTITY = 24 WHERE ID = 5;

SELECT * FROM PETSALE;

ALTER TABLE PETSALE
DROP COLUMN Profit;

SELECT * FROM PETSALE;

ALTER TABLE PETSALE 
ALTER COLUMN Pet SET DATA TYPE VARCHAR(20);

ALTER TABLE PETSALE 
RENAME COLUMN Pet TO Animal;

TRUNCATE TABLE FARMPET IMMEDIATE;

DROP TABLE FARMPET;
SELECT * FROM FARMPET;






